export {ArticalDetail} from "./ui/ArticalDetail/ArticalDetail"
export type {Article} from "./model/types/Article"
export type {ArticalDetailsSchema} from "./model/types/ArticalDetailsSchema"
export {ArticalDetailsReducer, ArticalDetailsActions} from "./model/slice/ArticalDetailsSlice"
export {getArticleSelectorData, getArticleSelectorErorr, getArticleSelectorIsloading} from "./model/selectors/getArticleSelector"